#define RGB_MATRIX_DEFAULT_HUE 7
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_WIDE_REACTIVE_BACKLIGHT
#define RGB_MATRIX_TIMEOUT 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_SPD 25

#define CAPS_LOCK_CUSTOM_LED_R 255
#define CAPS_LOCK_CUSTOM_LED_G 40
#define CAPS_LOCK_CUSTOM_LED_B 0

#define NUM_LOCK_CUSTOM_LED_R 255
#define NUM_LOCK_CUSTOM_LED_G 40
#define NUM_LOCK_CUSTOM_LED_B 0

#define LED_HITS_TO_REMEMBER 16