#define RGB_MATRIX_DEFAULT_HUE 13
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_WIDE_REACTIVE_BACKLIGHT
#define RGB_MATRIX_TIMEOUT 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_SPD 15

#if KEYBOARD_framework_macropad
#define RGB_MATRIX_DEFAULT_VAL 170
#endif

#define NUM_LOCK_CUSTOM_LED_R 200
#define NUM_LOCK_CUSTOM_LED_G 80
#define NUM_LOCK_CUSTOM_LED_B 17
#define RCVMIN 100

#if KEYBOARD_framework_ansi
#define RCVPOWER 4
#endif

#define LED_HITS_TO_REMEMBER 20
