#define RGB_MATRIX_DEFAULT_HUE 13
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_multicolor_map
#define RGB_MATRIX_TIMEOUT 0
#define RGB_MATRIX_DEFAULT_SAT 60
#define RGB_MATRIX_DEFAULT_SPD 15

#if KEYBOARD_framework_macropad
#define RGB_MATRIX_DEFAULT_VAL 85
#endif

#define NUM_LOCK_CUSTOM_LED_R 255
#define NUM_LOCK_CUSTOM_LED_G 100
#define NUM_LOCK_CUSTOM_LED_B 0
#define RCVMIN 100

#define LED_HITS_TO_REMEMBER 20
